[tox]
envlist = lint, format, test

[testenv:test]
deps =
    pytest
    tzlocal
commands =
    pytest {posargs:tests/}

[testenv:lint]
skip_install = true
deps =
    ruff
commands =
    ruff check {posargs:logflux/ tests/}

[testenv:format]
skip_install = true
deps =
    black
commands =
    black --check {posargs:logflux/ tests/}
